# -*- coding: utf-8 -*-
"""Sin midsem code .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYm3jiAC_ugQnYyc_UKNKqBq78WyWc4s
"""

# Much simpler — no torch-geometric needed!
!pip install scikit-learn pandas numpy tqdm -q
!pip install torch --index-url https://download.pytorch.org/whl/cu118 -q

import torch
print("✅ Done! PyTorch version:", torch.__version__)
print("✅ GPU available:", torch.cuda.is_available())

import os

# Clone the official HGAT repo
!git clone https://github.com/YuxiangRen/Hierarchical-Graph-Attention-Network.git
os.chdir('Hierarchical-Graph-Attention-Network')
!ls
print("✅ Repo cloned")

from google.colab import files
import os

# Run this cell — it will open a file picker dialog
# Upload all 4 files:
#   politifact_real.csv
#   politifact_fake.csv
#   gossipcop_real.csv
#   gossipcop_fake.csv

uploaded = files.upload()
print("Uploaded files:", list(uploaded.keys()))

import pandas as pd

# Load datasets
pf_real = pd.read_csv('politifact_real.csv')
pf_fake = pd.read_csv('politifact_fake.csv')
gc_real = pd.read_csv('gossipcop_real.csv')
gc_fake = pd.read_csv('gossipcop_fake.csv')

print("=== PolitiFact Real ===")
print(pf_real.shape, "\n", pf_real.head(2))

print("\n=== PolitiFact Fake ===")
print(pf_fake.shape, "\n", pf_fake.head(2))

print("\n=== GossipCop Real ===")
print(gc_real.shape, "\n", gc_real.head(2))

print("\n=== GossipCop Fake ===")
print(gc_fake.shape, "\n", gc_fake.head(2))

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
import scipy.sparse as sp

def build_hin(real_df, fake_df, dataset_name="politifact"):
    """
    Build a News-HIN from real/fake CSVs.
    Nodes: News Articles, Creators (extracted from URL domain), Subjects (inferred from title keywords)
    Links: creator→article, article→subject
    """
    # Add labels
    real_df = real_df.copy()
    fake_df = fake_df.copy()
    real_df['label'] = 0  # real
    fake_df['label'] = 1  # fake

    # Combine
    df = pd.concat([real_df, fake_df], ignore_index=True)
    df['title'] = df['title'].fillna('')
    df['news_url'] = df['news_url'].fillna('')

    # ── News Article Features (TF-IDF on title) ──────────────────
    vectorizer_news = TfidfVectorizer(max_features=3000, stop_words='english')
    news_features = vectorizer_news.fit_transform(df['title'])  # (N_articles, 3000)

    # ── Creator nodes (domain of URL as proxy for creator) ─────────
    def extract_domain(url):
        try:
            from urllib.parse import urlparse
            domain = urlparse(url if url.startswith('http') else 'http://'+url).netloc
            return domain if domain else 'unknown'
        except:
            return 'unknown'

    df['creator'] = df['news_url'].apply(extract_domain)
    creators = df['creator'].unique().tolist()
    creator2id = {c: i for i, c in enumerate(creators)}
    df['creator_id'] = df['creator'].map(creator2id)

    # Creator features: TF-IDF on URL text
    vectorizer_creator = TfidfVectorizer(max_features=500, analyzer='char_wb', ngram_range=(2,4))
    creator_texts = [c for c in creators]
    creator_features = vectorizer_creator.fit_transform(creator_texts)

    # ── Subject nodes (simple keyword binning from title) ──────────
    # Use top TF-IDF terms per article as subject tags (simplified)
    vectorizer_subject = TfidfVectorizer(max_features=100, stop_words='english')
    subject_matrix = vectorizer_subject.fit_transform(df['title'])
    # Each article's top subject = argmax of its TF-IDF row
    top_subject_ids = np.array(subject_matrix.argmax(axis=1)).flatten()
    df['subject_id'] = top_subject_ids
    n_subjects = 100
    subject_features = np.eye(n_subjects, dtype=np.float32)  # identity (one-hot)

    # ── Adjacency: creator→article ─────────────────────────────────
    n_articles = len(df)
    n_creators = len(creators)
    row_c = df['creator_id'].values
    col_a = np.arange(n_articles)
    data_c = np.ones(n_articles)
    # Shape: (n_creators, n_articles)
    adj_creator_article = sp.csr_matrix(
        (data_c, (row_c, col_a)), shape=(n_creators, n_articles)
    )

    # ── Adjacency: article→subject ─────────────────────────────────
    row_a2 = np.arange(n_articles)
    col_s = df['subject_id'].values
    data_s = np.ones(n_articles)
    # Shape: (n_articles, n_subjects)
    adj_article_subject = sp.csr_matrix(
        (data_s, (row_a2, col_s)), shape=(n_articles, n_subjects)
    )

    labels = df['label'].values
    print(f"[{dataset_name}] Articles: {n_articles}, Creators: {n_creators}, Subjects: {n_subjects}")
    print(f"  Real: {(labels==0).sum()}, Fake: {(labels==1).sum()}")

    return {
        'news_features': news_features,        # scipy sparse (N_articles, 3000)
        'creator_features': creator_features,  # scipy sparse (N_creators, 500)
        'subject_features': subject_features,  # numpy (100, 100)
        'adj_ca': adj_creator_article,         # (N_creators, N_articles)
        'adj_as': adj_article_subject,         # (N_articles, 100)
        'labels': labels,
        'n_articles': n_articles,
        'n_creators': n_creators,
        'n_subjects': n_subjects,
        'df': df
    }

# Build HINs for both datasets
hin_politifact = build_hin(pf_real, pf_fake, "PolitiFact")
hin_gossipcop  = build_hin(gc_real, gc_fake, "GossipCop")
print("✅ HINs built")

import torch
import torch.nn as nn
import torch.nn.functional as F

class NodeLevelAttention(nn.Module):
    """Aggregates neighbors with a type-specific projection."""
    def __init__(self, target_dim, neighbor_dim, out_dim):
        super().__init__()
        self.W_target   = nn.Linear(target_dim,   out_dim, bias=False)
        self.W_neighbor = nn.Linear(neighbor_dim, out_dim, bias=False)

    def forward(self, h_target, h_neighbors, adj):
        """
        h_target:    (N_target, target_dim)
        h_neighbors: (N_neighbor, neighbor_dim)
        adj:         tensor (N_target, N_neighbor)
        Returns:     (N_target, out_dim)
        """
        h_n = self.W_neighbor(h_neighbors)   # (N_neighbor, out_dim)

        # Normalize adjacency rows
        row_sum = adj.sum(dim=1, keepdim=True).clamp(min=1e-8)
        adj_norm = adj / row_sum              # (N_target, N_neighbor)

        # Aggregate
        out = torch.mm(adj_norm, h_n)         # (N_target, out_dim)
        return F.elu(out)


class SchemaLevelAttention(nn.Module):
    def __init__(self, schema_dim):
        super().__init__()
        self.score = nn.Linear(schema_dim * 2, 1)

    def forward(self, target_repr, schema_nodes):
        scores = []
        for sn in schema_nodes:
            combined = torch.cat([target_repr, sn], dim=1)
            scores.append(self.score(combined))
        weights = F.softmax(torch.cat(scores, dim=1), dim=1)  # (N, K)
        schema_stack = torch.stack(schema_nodes, dim=2)        # (N, D, K)
        return (schema_stack * weights.unsqueeze(1)).sum(dim=2)


class HGAT(nn.Module):
    def __init__(self, dim_news, dim_creator, dim_subject, hidden_dim=64, n_classes=2):
        super().__init__()
        self.hidden_dim = hidden_dim

        # Each attention uses the correct input dimensions
        self.attn_self    = NodeLevelAttention(dim_news,    dim_news,    hidden_dim)
        self.attn_creator = NodeLevelAttention(dim_news,    dim_creator, hidden_dim)
        self.attn_subject = NodeLevelAttention(dim_news,    dim_subject, hidden_dim)

        self.schema_attn = SchemaLevelAttention(hidden_dim)

        self.classifier = nn.Sequential(
            nn.Linear(hidden_dim, 32),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(32, n_classes)
        )

    def forward(self, h_news, h_creator, h_subject, adj_ca, adj_as):
        """
        adj_ca: (N_articles, N_creators)  — needs transpose of original
        adj_as: (N_articles, N_subjects)
        """
        N = h_news.size(0)

        # Self schema node: article attends to itself (identity adjacency)
        schema_N = self.attn_self(h_news, h_news,
                                  torch.eye(N, device=h_news.device))

        # Creator schema node: adj_ca is (N_creators, N_articles), transpose -> (N_articles, N_creators)
        schema_C = self.attn_creator(h_news, h_creator, adj_ca.t())

        # Subject schema node: adj_as is (N_articles, N_subjects)
        schema_S = self.attn_subject(h_news, h_subject, adj_as)

        # Schema-level fusion
        r_ni = self.schema_attn(schema_N, [schema_N, schema_C, schema_S])

        return self.classifier(r_ni)

print("✅ HGAT model re-defined with correct dimensions")

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
import torch
import torch.nn as nn

def sparse_to_tensor(sparse_mat):
    dense = sparse_mat.toarray() if hasattr(sparse_mat, 'toarray') else np.array(sparse_mat)
    return torch.FloatTensor(dense)

def prepare_tensors(hin):
    news_feat    = sparse_to_tensor(hin['news_features'])
    creator_feat = sparse_to_tensor(hin['creator_features'])
    subject_feat = torch.FloatTensor(hin['subject_features'])
    adj_ca       = torch.FloatTensor(hin['adj_ca'].toarray())
    adj_as       = torch.FloatTensor(hin['adj_as'].toarray())
    labels       = torch.LongTensor(hin['labels'])
    return news_feat, creator_feat, subject_feat, adj_ca, adj_as, labels


def run_experiment(hin, dataset_name, train_ratio=0.8, epochs=100, lr=0.005):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"\n{'='*50}")
    print(f"Dataset: {dataset_name} | Train ratio: {train_ratio} | Device: {device}")
    print('='*50)

    news_feat, creator_feat, subject_feat, adj_ca, adj_as, labels = prepare_tensors(hin)

    n = len(labels)
    indices = np.arange(n)
    train_idx, temp_idx = train_test_split(
        indices, train_size=train_ratio, stratify=labels.numpy(), random_state=42
    )
    val_idx, test_idx = train_test_split(
        temp_idx, test_size=0.5, stratify=labels.numpy()[temp_idx], random_state=42
    )

    # ── Build model (no n_heads argument) ──────────────────────────
    model = HGAT(
        dim_news    = news_feat.size(1),
        dim_creator = creator_feat.size(1),
        dim_subject = subject_feat.size(1),
        hidden_dim  = 64,
        n_classes   = 2
    ).to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=5e-4)
    criterion = nn.CrossEntropyLoss()

    news_feat    = news_feat.to(device)
    creator_feat = creator_feat.to(device)
    subject_feat = subject_feat.to(device)
    adj_ca       = adj_ca.to(device)
    adj_as       = adj_as.to(device)
    labels       = labels.to(device)

    best_val_acc = 0
    best_state   = None

    for epoch in range(1, epochs + 1):
        model.train()
        optimizer.zero_grad()
        logits = model(news_feat, creator_feat, subject_feat, adj_ca, adj_as)
        loss   = criterion(logits[train_idx], labels[train_idx])
        loss.backward()
        optimizer.step()

        if epoch % 10 == 0:
            model.eval()
            with torch.no_grad():
                val_logits = model(news_feat, creator_feat, subject_feat, adj_ca, adj_as)
                preds      = val_logits.argmax(dim=1).cpu().numpy()
                val_acc    = accuracy_score(labels.cpu().numpy()[val_idx], preds[val_idx])

            if val_acc > best_val_acc:
                best_val_acc = val_acc
                best_state   = {k: v.clone() for k, v in model.state_dict().items()}

            print(f"  Epoch {epoch:3d} | Loss: {loss.item():.4f} | Val Acc: {val_acc:.4f}")

    if best_state:
        model.load_state_dict(best_state)

    model.eval()
    with torch.no_grad():
        logits = model(news_feat, creator_feat, subject_feat, adj_ca, adj_as)
        preds  = logits.argmax(dim=1).cpu().numpy()
        y_true = labels.cpu().numpy()

    acc  = accuracy_score(y_true[test_idx],  preds[test_idx])
    f1   = f1_score(y_true[test_idx],        preds[test_idx], average='binary')
    prec = precision_score(y_true[test_idx], preds[test_idx], average='binary', zero_division=0)
    rec  = recall_score(y_true[test_idx],    preds[test_idx], average='binary')

    print(f"\n📊 Test Results (train={train_ratio}):")
    print(f"  Accuracy : {acc:.4f}")
    print(f"  F1       : {f1:.4f}")
    print(f"  Precision: {prec:.4f}")
    print(f"  Recall   : {rec:.4f}")

    return {'acc': acc, 'f1': f1, 'precision': prec, 'recall': rec}

print("✅ Utilities re-defined")

# Run with 80% train ratio (as in the paper)
results_pf_80 = run_experiment(
    hin          = hin_politifact,
    dataset_name = "PolitiFact",
    train_ratio  = 0.8,
    epochs       = 100,
    lr           = 0.005
)

results_gc_80 = run_experiment(
    hin          = hin_gossipcop,
    dataset_name = "GossipCop",
    train_ratio  = 0.8,
    epochs       = 100,
    lr           = 0.005
)

def run_experiment_fast(hin, dataset_name, train_ratio=0.8, epochs=50, lr=0.005, batch_size=512):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"\n{'='*50}")
    print(f"Dataset: {dataset_name} | Train ratio: {train_ratio} | Device: {device}")
    print('='*50)

    news_feat, creator_feat, subject_feat, adj_ca, adj_as, labels = prepare_tensors(hin)

    # adj_ca is (N_creators, N_articles) — transpose to (N_articles, N_creators)
    adj_ac = adj_ca.t()   # (N_articles, N_creators)

    n = len(labels)
    indices = np.arange(n)
    train_idx, temp_idx = train_test_split(
        indices, train_size=train_ratio, stratify=labels.numpy(), random_state=42
    )
    val_idx, test_idx = train_test_split(
        temp_idx, test_size=0.5, stratify=labels.numpy()[temp_idx], random_state=42
    )

    model = HGAT(
        dim_news    = news_feat.size(1),
        dim_creator = creator_feat.size(1),
        dim_subject = subject_feat.size(1),
        hidden_dim  = 32,
        n_classes   = 2
    ).to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=5e-4)
    criterion = nn.CrossEntropyLoss()

    best_val_acc = 0
    best_state   = None

    for epoch in range(1, epochs + 1):
        model.train()
        optimizer.zero_grad()

        # Sample batch from article indices
        batch = np.random.choice(train_idx, size=min(batch_size, len(train_idx)), replace=False)

        # Index rows (articles) correctly
        news_batch    = news_feat[batch, :]   # (batch, dim_news)
        adj_ac_batch  = adj_ac[batch, :]      # (batch, N_creators)
        adj_as_batch  = adj_as[batch, :]      # (batch, N_subjects)

        # Model expects adj_ca as (N_creators, N_articles) so transpose back
        logits = model(news_batch, creator_feat, subject_feat,
                       adj_ac_batch.t(), adj_as_batch)
        loss   = criterion(logits, labels[batch])
        loss.backward()
        optimizer.step()

        if epoch % 5 == 0:
            model.eval()
            with torch.no_grad():
                val_sample    = np.random.choice(val_idx, size=min(300, len(val_idx)), replace=False)
                news_val      = news_feat[val_sample, :]
                adj_ac_val    = adj_ac[val_sample, :]
                adj_as_val    = adj_as[val_sample, :]

                val_logits = model(news_val, creator_feat, subject_feat,
                                   adj_ac_val.t(), adj_as_val)
                preds   = val_logits.argmax(dim=1).cpu().numpy()
                val_acc = accuracy_score(labels.numpy()[val_sample], preds)

            if val_acc > best_val_acc:
                best_val_acc = val_acc
                best_state   = {k: v.clone() for k, v in model.state_dict().items()}

            print(f"  Epoch {epoch:3d} | Loss: {loss.item():.4f} | Val Acc: {val_acc:.4f}")

    if best_state:
        model.load_state_dict(best_state)

    # Test
    model.eval()
    all_preds  = []
    test_array = np.array(test_idx)

    with torch.no_grad():
        for i in range(0, len(test_array), batch_size):
            batch      = test_array[i:i+batch_size]
            news_b     = news_feat[batch, :]
            adj_ac_b   = adj_ac[batch, :]
            adj_as_b   = adj_as[batch, :]
            logits     = model(news_b, creator_feat, subject_feat,
                               adj_ac_b.t(), adj_as_b)
            all_preds.append(logits.argmax(dim=1).cpu().numpy())

    preds  = np.concatenate(all_preds)
    y_true = labels.numpy()[test_idx]

    acc  = accuracy_score(y_true,  preds)
    f1   = f1_score(y_true,        preds, average='binary')
    prec = precision_score(y_true, preds, average='binary', zero_division=0)
    rec  = recall_score(y_true,    preds, average='binary')

    print(f"\n📊 Test Results (train={train_ratio}):")
    print(f"  Accuracy : {acc:.4f}")
    print(f"  F1       : {f1:.4f}")
    print(f"  Precision: {prec:.4f}")
    print(f"  Recall   : {rec:.4f}")

    return {'acc': acc, 'f1': f1, 'precision': prec, 'recall': rec}

print("✅ run_experiment_fast fixed and defined")

train_ratios = [0.2, 0.4, 0.6, 0.8]
all_results  = {}

for dataset_name, hin in [("PolitiFact", hin_politifact), ("GossipCop", hin_gossipcop)]:
    all_results[dataset_name] = {}
    for ratio in train_ratios:
        print(f"\nRunning {dataset_name} | Train ratio: {ratio}")
        if dataset_name == "GossipCop":
            res = run_experiment_fast(hin, dataset_name, train_ratio=ratio, epochs=40)
        else:
            res = run_experiment(hin, dataset_name, train_ratio=ratio, epochs=60)
        all_results[dataset_name][ratio] = res

print("\n" + "="*70)
print("SUMMARY TABLE — HGAT Results")
print("="*70)
for ds in ["PolitiFact", "GossipCop"]:
    print(f"\n📰 {ds}")
    print(f"  {'Train%':>6} {'Accuracy':>10} {'F1':>8} {'Precision':>12} {'Recall':>9}")
    print(f"  {'-'*50}")
    for ratio, res in all_results[ds].items():
        print(f"  {int(ratio*100):>5}%  {res['acc']:>10.4f} {res['f1']:>8.4f} {res['precision']:>12.4f} {res['recall']:>9.4f}")

import matplotlib.pyplot as plt

fig, axes = plt.subplots(2, 4, figsize=(18, 8))
fig.suptitle("HGAT Fake News Detection Results", fontsize=14, fontweight='bold')

metrics  = ['acc', 'f1', 'precision', 'recall']
m_labels = ['Accuracy', 'F1', 'Precision', 'Recall']
colors   = {'PolitiFact': 'steelblue', 'GossipCop': 'darkorange'}

for row_i, ds in enumerate(["PolitiFact", "GossipCop"]):
    for col_i, (m, ml) in enumerate(zip(metrics, m_labels)):
        ax   = axes[row_i][col_i]
        rats = list(all_results[ds].keys())
        vals = [all_results[ds][r][m] for r in rats]

        ax.plot([r*100 for r in rats], vals,
                color=colors[ds], marker='o',
                linewidth=2, markersize=7, label='HGAT')
        ax.set_title(f"{ds} — {ml}", fontsize=10)
        ax.set_xlabel("Train Ratio (%)")
        ax.set_ylabel(ml)
        ax.set_xticks([20, 40, 60, 80])
        ax.set_ylim(0, 1)
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=8)

plt.tight_layout()
plt.savefig('hgat_results.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Plot saved as hgat_results.png")

import pandas as pd

rows = []
for ds in ["PolitiFact", "GossipCop"]:
    for ratio, res in all_results[ds].items():
        rows.append({
            'Dataset'  : ds,
            'Train_%'  : int(ratio * 100),
            'Accuracy' : round(res['acc'], 4),
            'F1'       : round(res['f1'],  4),
            'Precision': round(res['precision'], 4),
            'Recall'   : round(res['recall'],    4)
        })

results_df = pd.DataFrame(rows)
results_df.to_csv('hgat_results.csv', index=False)
print(results_df.to_string(index=False))
print("\n✅ Saved to hgat_results.csv")

from google.colab import files
files.download('hgat_results.csv')

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from urllib.parse import urlparse
import scipy.sparse as sp

def build_hin_leakage_free(real_df, fake_df, dataset_name="politifact",
                            base_train_ratio=0.8, random_state=42):
    """
    Builds HIN with ALL vectorizers fitted ONLY on the training split.
    Returns hin dict with an additional 'global_train_mask' boolean array.

    Key fix: TF-IDF for news titles, creator char-ngrams, and subject bins
    are all fit exclusively on the training articles, then *transformed* on
    the full dataset. Test articles therefore never influence the feature space.
    """
    real_df = real_df.copy(); fake_df = fake_df.copy()
    real_df['label'] = 0;     fake_df['label'] = 1
    df = pd.concat([real_df, fake_df], ignore_index=True)
    df['title']    = df['title'].fillna('')
    df['news_url'] = df['news_url'].fillna('')

    # ── Global split FIRST — before any fitting ─────────────────────────────
    n      = len(df)
    labels = df['label'].values
    all_idx = np.arange(n)
    train_idx, test_idx = train_test_split(
        all_idx, train_size=base_train_ratio,
        stratify=labels, random_state=random_state
    )
    train_mask = np.zeros(n, dtype=bool)
    train_mask[train_idx] = True

    train_titles = df['title'].iloc[train_idx]

    # ── News features: fit on TRAIN only ────────────────────────────────────
    vec_news = TfidfVectorizer(max_features=3000, stop_words='english')
    vec_news.fit(train_titles)
    news_features = vec_news.transform(df['title'])          # (N, 3000)

    # ── Creator nodes ───────────────────────────────────────────────────────
    def extract_domain(url):
        try:
            domain = urlparse(url if str(url).startswith('http') else 'http://'+str(url)).netloc
            return domain if domain else 'unknown'
        except:
            return 'unknown'

    df['creator'] = df['news_url'].apply(extract_domain)
    # Build creator vocab from TRAIN only
    train_creators = df['creator'].iloc[train_idx].unique().tolist()
    # Unknown creator for unseen test domains
    if 'unknown' not in train_creators:
        train_creators.append('unknown')
    creator2id = {c: i for i, c in enumerate(train_creators)}
    df['creator_id'] = df['creator'].map(creator2id).fillna(creator2id['unknown']).astype(int)

    vec_creator = TfidfVectorizer(max_features=500, analyzer='char_wb', ngram_range=(2, 4))
    vec_creator.fit(train_creators)
    creator_features = vec_creator.transform(train_creators)  # (N_train_creators, 500)

    # ── Subject nodes: top-100 TF-IDF terms, vocab from TRAIN only ─────────
    vec_subject = TfidfVectorizer(max_features=100, stop_words='english')
    vec_subject.fit(train_titles)
    subject_matrix   = vec_subject.transform(df['title'])
    top_subject_ids  = np.array(subject_matrix.argmax(axis=1)).flatten()
    df['subject_id'] = top_subject_ids
    n_subjects       = 100
    subject_features = np.eye(n_subjects, dtype=np.float32)

    # ── Adjacency matrices ──────────────────────────────────────────────────
    n_articles = n
    n_creators = len(train_creators)

    row_c = df['creator_id'].values
    col_a = np.arange(n_articles)
    adj_creator_article = sp.csr_matrix(
        (np.ones(n_articles), (row_c, col_a)),
        shape=(n_creators, n_articles)
    )

    row_a2 = np.arange(n_articles)
    col_s  = df['subject_id'].values
    adj_article_subject = sp.csr_matrix(
        (np.ones(n_articles), (row_a2, col_s)),
        shape=(n_articles, n_subjects)
    )

    print(f"[{dataset_name}] Articles: {n_articles}, Train: {train_mask.sum()}, "
          f"Test: {(~train_mask).sum()}")
    print(f"  Real: {(labels==0).sum()}, Fake: {(labels==1).sum()}")
    print(f"  Creators (train vocab): {n_creators}")

    return {
        'news_features'  : news_features,
        'creator_features': creator_features,
        'subject_features': subject_features,
        'adj_ca'         : adj_creator_article,
        'adj_as'         : adj_article_subject,
        'labels'         : labels,
        'n_articles'     : n_articles,
        'n_creators'     : n_creators,
        'n_subjects'     : n_subjects,
        'df'             : df,
        'global_train_mask': train_mask,   # NEW — used by temporal cells
    }

# Rebuild HINs (replaces the original hin_politifact / hin_gossipcop)
hin_politifact = build_hin_leakage_free(pf_real, pf_fake, "PolitiFact")
hin_gossipcop  = build_hin_leakage_free(gc_real, gc_fake, "GossipCop")
print("✅ Leakage-free HINs built")

def add_temporal_snapshots(hin, dataset_name):
    """
    Assigns snapshot labels (0=Early, 1=Middle, 2=Late) using ONLY the
    global_train_mask ordering — test articles are binned by their
    position but the bin boundaries come from training data quantiles only.

    This prevents the sort-key from carrying future label information
    into the snapshot boundaries.
    """
    from urllib.parse import urlparse
    df           = hin['df']
    train_mask   = hin['global_train_mask']
    timestamp_col = None

    for col in ['publish_date', 'date', 'published', 'timestamp']:
        if col in df.columns:
            timestamp_col = col
            break

    if timestamp_col:
        ts = pd.to_datetime(df[timestamp_col], errors='coerce')
        df['_creator'] = df['news_url'].apply(
            lambda u: urlparse(u if str(u).startswith('http') else 'http://'+str(u)).netloc
        )
        # Impute only within training articles to avoid leakage
        train_ts = ts[train_mask]
        group_median = (df.loc[train_mask]
                          .groupby('_creator')
                          .apply(lambda g: pd.to_datetime(ts[g.index], errors='coerce').median()))
        for i in df.index[~train_mask & ts.isna()]:
            creator = df.at[i, '_creator']
            ts.at[i] = group_median.get(creator, train_ts.median())
        ts = ts.fillna(train_ts.median())
        sort_key = ts.rank(method='first')
        print(f"[{dataset_name}] Using timestamp column: '{timestamp_col}'")
    else:
        print(f"[{dataset_name}] ⚠️  No timestamp — using row order as proxy")
        sort_key = pd.Series(np.arange(len(df)), index=df.index)

    # Compute bin edges from TRAIN only, apply to all
    train_sort  = sort_key[train_mask]
    q33, q67    = np.percentile(train_sort, [33.33, 66.67])
    snapshots   = np.where(sort_key <= q33, 0, np.where(sort_key <= q67, 1, 2))

    hin['snapshot'] = snapshots
    counts = {i: (snapshots == i).sum() for i in [0, 1, 2]}
    print(f"[{dataset_name}] Snapshots → Early: {counts[0]}, Middle: {counts[1]}, Late: {counts[2]}")

from urllib.parse import urlparse
add_temporal_snapshots(hin_politifact, "PolitiFact")
add_temporal_snapshots(hin_gossipcop,  "GossipCop")
print("✅ Temporal snapshots assigned (leakage-free boundaries)")

import torch
import torch.nn as nn
import torch.nn.functional as F

class NodeLevelAttention(nn.Module):
    def __init__(self, neighbor_dim, out_dim):
        super().__init__()
        self.W = nn.Linear(neighbor_dim, out_dim, bias=False)

    def forward(self, h_neighbors, adj):
        h_n     = self.W(h_neighbors)
        row_sum = adj.sum(dim=1, keepdim=True).clamp(min=1e-8)
        return F.elu(torch.mm(adj / row_sum, h_n))

class SchemaLevelAttention(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.score = nn.Linear(dim * 2, 1)

    def forward(self, anchor, views):
        w = F.softmax(
            torch.cat([self.score(torch.cat([anchor, v], dim=1)) for v in views], dim=1),
            dim=1
        )
        return (torch.stack(views, dim=2) * w.unsqueeze(1)).sum(dim=2)

class HGATEmbedder(nn.Module):
    def __init__(self, dim_news, dim_creator, dim_subject, hidden_dim=64):
        super().__init__()
        self.proj_news    = nn.Linear(dim_news,    hidden_dim, bias=False)
        self.attn_creator = NodeLevelAttention(dim_creator, hidden_dim)
        self.attn_subject = NodeLevelAttention(dim_subject, hidden_dim)
        self.schema       = SchemaLevelAttention(hidden_dim)

    def forward(self, h_news, h_creator, h_subject, adj_ca, adj_as):
        adj_ac       = adj_ca.t()
        news_proj    = F.elu(self.proj_news(h_news))
        creator_repr = self.attn_creator(h_creator, adj_ac)
        subject_repr = self.attn_subject(h_subject, adj_as)
        return self.schema(news_proj, [creator_repr, subject_repr])

class TemporalHGAT(nn.Module):
    def __init__(self, hidden_dim=64, lstm_hidden=64, dropout=0.4):
        super().__init__()
        self.lstm = nn.LSTM(hidden_dim, lstm_hidden, batch_first=True)
        self.head = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(lstm_hidden, 32),
            nn.ReLU(),
            nn.Linear(32, 2)
        )

    def forward(self, x):          # (batch, 3, hidden_dim)
        _, (h, _) = self.lstm(x)
        return self.head(h[-1])

print("✅ HGATEmbedder + TemporalHGAT defined")

import scipy.sparse as sp

def sparse_to_dense(sp_mat, device):
    return torch.tensor(sp_mat.toarray().astype(np.float32), device=device)

def train_snapshot_embedder(hin, snap_id, train_mask_global,
                             hidden_dim=64, epochs=80, lr=0.005):
    """
    Trains the HGAT embedder ONLY on articles that are:
      (a) in snapshot snap_id  AND
      (b) in the global training split

    Then embeds ALL articles in that snapshot (train + test) using the
    trained (frozen) embedder — no weight updates from test articles.
    """
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    snap_mask        = hin['snapshot'] == snap_id
    snap_idx_all     = np.where(snap_mask)[0]                # all articles in snapshot
    snap_train_idx   = np.where(snap_mask & train_mask_global)[0]   # train-only subset

    name = ['Early', 'Middle', 'Late'][snap_id]
    print(f"    [{name}] total={len(snap_idx_all)}, train={len(snap_train_idx)}")

    if len(snap_train_idx) == 0:
        print(f"    [{name}] ⚠️  No training articles — using zeros")
        hidden_embs = torch.zeros(len(snap_idx_all), hidden_dim)
        return hidden_embs, snap_idx_all

    # ── Build features for ALL snapshot articles (transform only) ───────────
    news_all = torch.tensor(
        hin['news_features'][snap_idx_all].toarray(), dtype=torch.float32, device=device
    )
    adj_as_all = sparse_to_dense(hin['adj_as'][snap_idx_all, :], device)

    df_snap_all = hin['df'].iloc[snap_idx_all]

    # Creator subset: only creators seen in this snapshot's TRAIN articles
    df_snap_train   = hin['df'].iloc[snap_train_idx]
    train_creator_ids = np.unique(df_snap_train['creator_id'].values)
    global_to_local   = {g: l for l, g in enumerate(train_creator_ids)}

    creator_t = torch.tensor(
        hin['creator_features'][train_creator_ids].toarray(),
        dtype=torch.float32, device=device
    )
    subject_t = torch.tensor(hin['subject_features'], dtype=torch.float32, device=device)

    # Remap creator IDs for all snapshot articles (unseen → creator 0 as fallback)
    local_ids_all = np.array([
        global_to_local.get(cid, 0)
        for cid in df_snap_all['creator_id'].values
    ])
    n_local = len(train_creator_ids)
    adj_ca_all = torch.zeros(n_local, len(snap_idx_all), device=device)
    for art_local, cr_local in enumerate(local_ids_all):
        adj_ca_all[cr_local, art_local] = 1.0

    # ── Build features/adj for TRAINING articles only ───────────────────────
    # Map snap_train_idx positions to positions within snap_idx_all
    snap_idx_all_list   = list(snap_idx_all)
    train_positions_in_snap = [snap_idx_all_list.index(i) for i in snap_train_idx]

    news_tr   = news_all[train_positions_in_snap]
    adj_ca_tr = adj_ca_all[:, train_positions_in_snap]
    adj_as_tr = adj_as_all[train_positions_in_snap]

    # Local labels for training articles
    labels_tr = torch.tensor(
        hin['labels'][snap_train_idx], dtype=torch.long, device=device
    )

    # ── Build model ──────────────────────────────────────────────────────────
    embedder = HGATEmbedder(
        dim_news    = news_tr.shape[1],
        dim_creator = creator_t.shape[1],
        dim_subject = subject_t.shape[1],
        hidden_dim  = hidden_dim
    ).to(device)
    for p in embedder.parameters():
        if p.dim() > 1:
            nn.init.xavier_uniform_(p)

    n_fake = labels_tr.sum().item()
    n_real = len(labels_tr) - n_fake
    w          = torch.tensor([1.0, n_real / max(n_fake, 1)], device=device)
    classifier = nn.Sequential(nn.Linear(hidden_dim, 2)).to(device)
    optimizer  = torch.optim.Adam(
        list(embedder.parameters()) + list(classifier.parameters()),
        lr=lr, weight_decay=5e-4
    )
    criterion  = nn.CrossEntropyLoss(weight=w)

    best_loss, best_state = float('inf'), None

    for epoch in range(1, epochs + 1):
        embedder.train(); classifier.train()
        optimizer.zero_grad()

        emb  = embedder(news_tr, creator_t, subject_t, adj_ca_tr, adj_as_tr)
        if torch.isnan(emb).any():
            continue
        loss = criterion(classifier(emb), labels_tr)
        if torch.isnan(loss):
            continue
        loss.backward()
        torch.nn.utils.clip_grad_norm_(
            list(embedder.parameters()) + list(classifier.parameters()), max_norm=1.0
        )
        optimizer.step()

        if loss.item() < best_loss:
            best_loss  = loss.item()
            best_state = {k: v.clone() for k, v in embedder.state_dict().items()}

        if epoch % 20 == 0:
            print(f"    [{name}] Epoch {epoch:3d} | Loss: {loss.item():.4f}")

    # ── Embed ALL snapshot articles with frozen best embedder ────────────────
    if best_state:
        embedder.load_state_dict(best_state)
    embedder.eval()
    with torch.no_grad():
        all_embs = embedder(news_all, creator_t, subject_t, adj_ca_all, adj_as_all)

    if torch.isnan(all_embs).any():
        print(f"    [{name}] ⚠️  NaN in final embeddings — using zeros")
        all_embs = torch.zeros(len(snap_idx_all), hidden_dim)

    print(f"    [{name}] ✅ Done | best loss: {best_loss:.4f}")
    return all_embs.cpu(), snap_idx_all


def build_temporal_embeddings(hin, dataset_name, hidden_dim=64, epochs=80, lr=0.005):
    print(f"\n{'='*55}")
    print(f"Building temporal embeddings: {dataset_name}")
    print('='*55)
    n             = hin['n_articles']
    result        = np.zeros((n, 3, hidden_dim), dtype=np.float32)
    train_mask    = hin['global_train_mask']

    for snap_id in [0, 1, 2]:
        emb, idx = train_snapshot_embedder(
            hin, snap_id, train_mask, hidden_dim, epochs, lr
        )
        result[idx, snap_id, :] = emb.numpy()

    print(f"✅ Temporal embeddings shape: {result.shape}")
    return result

print("✅ Leakage-free snapshot helpers defined")

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

def run_temporal_experiment(hin, dataset_name, temporal_embs,
                             train_ratio=0.8, lstm_epochs=100, lr=0.005,
                             hidden_dim=64):
    """
    Uses hin['global_train_mask'] for the train/test split — the SAME split
    used when fitting the TF-IDF vectorizers. This guarantees no leakage
    between feature engineering, embedding, and evaluation.

    The train_ratio parameter here is used only to sub-sample the training
    set for the ablation study (matching the paper's 20/40/60/80% sweep).
    """
    print(f"\n── LSTM | {dataset_name} | train={int(train_ratio*100)}% ──")
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    labels           = hin['labels']
    global_train_idx = np.where(hin['global_train_mask'])[0]
    global_test_idx  = np.where(~hin['global_train_mask'])[0]

    # Sub-sample training set for the sweep while keeping test fixed
    if train_ratio < 0.8:
        sub_size  = int(len(global_train_idx) * (train_ratio / 0.8))
        sub_size  = max(sub_size, 10)
        rng       = np.random.default_rng(42)
        train_idx = rng.choice(global_train_idx, size=sub_size, replace=False)
    else:
        train_idx = global_train_idx

    # Val split from remaining training data
    remaining = np.setdiff1d(global_train_idx, train_idx)
    if len(remaining) > 0:
        val_idx = remaining
    else:
        # If nothing left (tiny datasets), just use train as val
        val_idx = train_idx

    test_idx = global_test_idx

    X = torch.tensor(temporal_embs, dtype=torch.float32)
    y = torch.tensor(labels,        dtype=torch.long)

    X_tr = X[train_idx].to(device);  y_tr = y[train_idx].to(device)
    X_va = X[val_idx].to(device);    y_va = y[val_idx].to(device)
    X_te = X[test_idx].to(device);   y_te = y[test_idx].to(device)

    n_fake = y_tr.sum().item()
    n_real = len(y_tr) - n_fake
    w      = torch.tensor([1.0, n_real / max(n_fake, 1)], device=device)

    model     = TemporalHGAT(hidden_dim=hidden_dim).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=5e-4)
    criterion = nn.CrossEntropyLoss(weight=w)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=30, gamma=0.5)

    best_val_f1, best_state = 0.0, None

    for epoch in range(1, lstm_epochs + 1):
        model.train()
        optimizer.zero_grad()
        criterion(model(X_tr), y_tr).backward()
        optimizer.step()
        scheduler.step()

        if epoch % 10 == 0:
            model.eval()
            with torch.no_grad():
                preds  = model(X_va).argmax(1).cpu().numpy()
            val_f1 = f1_score(y_va.cpu().numpy(), preds, average='binary', zero_division=0)
            val_ac = accuracy_score(y_va.cpu().numpy(), preds)
            if val_f1 > best_val_f1:
                best_val_f1 = val_f1
                best_state  = {k: v.clone() for k, v in model.state_dict().items()}
            print(f"  Epoch {epoch:3d} | Val Acc: {val_ac:.4f} | Val F1: {val_f1:.4f}")

    if best_state:
        model.load_state_dict(best_state)

    model.eval()
    with torch.no_grad():
        preds  = model(X_te).argmax(1).cpu().numpy()
    y_true = y_te.cpu().numpy()

    res = {
        'acc'      : accuracy_score(y_true, preds),
        'f1'       : f1_score(y_true, preds, average='binary', zero_division=0),
        'precision': precision_score(y_true, preds, average='binary', zero_division=0),
        'recall'   : recall_score(y_true, preds, average='binary', zero_division=0),
    }
    print(f"\n📊 Test | Acc: {res['acc']:.4f} | F1: {res['f1']:.4f} | "
          f"Prec: {res['precision']:.4f} | Rec: {res['recall']:.4f}")
    return res

print("✅ run_temporal_experiment (leakage-free) defined")

temp_embs_pf = build_temporal_embeddings(hin_politifact, "PolitiFact", hidden_dim=64, epochs=60)
temp_embs_gc = build_temporal_embeddings(hin_gossipcop,  "GossipCop",  hidden_dim=64, epochs=40)

train_ratios     = [0.2, 0.4, 0.6, 0.8]
temporal_results = {"PolitiFact": {}, "GossipCop": {}}

for ratio in train_ratios:
    temporal_results["PolitiFact"][ratio] = run_temporal_experiment(
        hin_politifact, "PolitiFact", temp_embs_pf, train_ratio=ratio)
    temporal_results["GossipCop"][ratio]  = run_temporal_experiment(
        hin_gossipcop,  "GossipCop",  temp_embs_gc, train_ratio=ratio)

print("\n✅ All Temporal-HGAT experiments complete!")

import matplotlib.pyplot as plt

static_results = {
    "PolitiFact": {0.2: {'acc': 0.7896, 'f1': 0.7063}, 0.4: {'acc': 0.8391, 'f1': 0.7773},
                   0.6: {'acc': 0.8208, 'f1': 0.7654}, 0.8: {'acc': 0.8679, 'f1': 0.8250}},
    "GossipCop":  {0.2: {'acc': 0.8463, 'f1': 0.6015}, 0.4: {'acc': 0.7980, 'f1': 0.2846},
                   0.6: {'acc': 0.8498, 'f1': 0.6380}, 0.8: {'acc': 0.8383, 'f1': 0.5558}},
}

print("=" * 80)
print("Static HGAT  vs  Temporal-HGAT (leakage-free)")
print("=" * 80)
for ds in ["PolitiFact", "GossipCop"]:
    print(f"\n📰 {ds}")
    print(f"  {'Train%':>6} | {'Stat Acc':>9} {'Temp Acc':>9} {'ΔAcc':>7} | "
          f"{'Stat F1':>8} {'Temp F1':>8} {'ΔF1':>7}")
    print(f"  {'-'*65}")
    for r in [0.2, 0.4, 0.6, 0.8]:
        s = static_results[ds][r]
        t = temporal_results[ds][r]
        print(f"  {int(r*100):>5}%  | {s['acc']:>9.4f} {t['acc']:>9.4f} {t['acc']-s['acc']:>+7.4f} | "
              f"{s['f1']:>8.4f} {t['f1']:>8.4f} {t['f1']-s['f1']:>+7.4f}")

fig, axes = plt.subplots(2, 2, figsize=(13, 8))
fig.suptitle("Static HGAT vs Temporal-HGAT (leakage-free)", fontsize=14, fontweight='bold')
ratios_pct = [20, 40, 60, 80]

for row_i, ds in enumerate(["PolitiFact", "GossipCop"]):
    for col_i, metric in enumerate(['acc', 'f1']):
        ax     = axes[row_i][col_i]
        s_vals = [static_results[ds][r][metric]   for r in [0.2, 0.4, 0.6, 0.8]]
        t_vals = [temporal_results[ds][r][metric] for r in [0.2, 0.4, 0.6, 0.8]]
        ax.plot(ratios_pct, s_vals, 'o--', color='#888780', label='Static HGAT',   linewidth=2, markersize=7)
        ax.plot(ratios_pct, t_vals, 'o-',  color='#378ADD', label='Temporal-HGAT', linewidth=2, markersize=7)
        ax.set_title(f"{ds} — {'Accuracy' if metric == 'acc' else 'F1 Score'}")
        ax.set_xlabel("Train Ratio (%)"); ax.set_ylabel(metric.upper())
        ax.set_ylim(0, 1); ax.set_xticks(ratios_pct)
        ax.grid(True, alpha=0.3); ax.legend()

plt.tight_layout()
plt.savefig('temporal_vs_static.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Plot saved")

# Save CSV
rows = []
for ds in ["PolitiFact", "GossipCop"]:
    for r in [0.2, 0.4, 0.6, 0.8]:
        s = static_results[ds][r]
        t = temporal_results[ds][r]
        rows.append({
            'Dataset': ds, 'Train_%': int(r * 100),
            'Static_Acc':   round(s['acc'],         4),
            'Temporal_Acc': round(t['acc'],         4),
            'Static_F1':    round(s['f1'],          4),
            'Temporal_F1':  round(t['f1'],          4),
            'Temporal_Prec': round(t['precision'],  4),
            'Temporal_Rec':  round(t['recall'],     4),
        })

df_final = pd.DataFrame(rows)
df_final.to_csv('temporal_hgat_results.csv', index=False)
print(df_final.to_string(index=False))

# Uncomment in Colab:
# from google.colab import files
# files.download('temporal_hgat_results.csv')
# files.download('temporal_vs_static.png')
print("✅ All done!")